In [1]:
#import dependencies
import pandas as pd
import numpy as np

In [16]:
# Name of the CSV File
ins_file_2010 = "Resources/2010_US_Ins_Cov.csv"
ins_file_2012 = "Resources/2012_US_Ins_Cov.csv"
ins_file_2014 = "Resources/2014_Us_Ins_Cov.csv"
ins_file_2016 = "Resources/2016_Us_Ins_Cov.csv"
ins_file_2018 = "Resources/2018_Us_Ins_Cov.csv"

In [17]:
# Read CSV Files
ins_df_2010 = pd.read_csv(ins_file_2010, names=["Location", "Employer", "Non-Group", "Medicaid", "Medicare",
       "Military", "Uninsured", "Total"], header=0)
ins_df_2012 = pd.read_csv(ins_file_2012, names=['Location', 'Employer', 'Non-Group', 'Medicaid', 'Medicare',
       'Military', 'Uninsured', 'Total'], header=0)
ins_df_2014 = pd.read_csv(ins_file_2014, names=['Location', 'Employer', 'Non-Group', 'Medicaid', 'Medicare',
       'Military', 'Uninsured', 'Total'], header=0)
ins_df_2016 = pd.read_csv(ins_file_2016, names=['Location', 'Employer', 'Non-Group', 'Medicaid', 'Medicare',
       'Military', 'Uninsured', 'Total'], header=0)
ins_df_2018 = pd.read_csv(ins_file_2018, names=['Location', 'Employer', 'Non-Group', 'Medicaid', 'Medicare',
       'Military', 'Uninsured', 'Total'], header=0)

## US Insurance Coverage 2010 : Health Insurance Coverage of Females 19-64

In [4]:
ins_df_2010

,Location,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,0.589,0.065,0.121,0.018,0.015,0.192,1
1,Alabama,0.575,0.063,0.115,0.032,0.021,0.194,1
2,Alaska,0.581,0.032,0.105,0.014,0.063,0.205,1
3,Arizona,0.529,0.065,0.171,0.016,0.018,0.201,1
4,Arkansas,0.522,0.058,0.117,0.041,0.019,0.244,1
5,California,0.540,0.080,0.131,0.012,0.010,0.225,1
6,Colorado,0.599,0.094,0.088,0.013,0.024,0.182,1
7,Connecticut,0.679,0.061,0.130,0.019,0.007,0.104,1
8,Delaware,0.629,0.046,0.172,0.026,0.015,0.112,1
9,District of Columbia,0.621,0.059,0.230,0.010,0.008,0.072,1
10,Florida,0.516,0.075,0.097,0.021,0.019,0.271,1
11,Georgia,0.561,0.059,0.089,0.021,0.023,0.248,1
12,Hawaii,0.662,0.068,0.123,0.012,0.050,0.085,1
13,Idaho,0.560,0.103,0.072,0.016,0.014,0.234,1
14,Illinois,0.617,0.062,0.125,0.016,0.005,0.175,1
15,Indiana,0.618,0.058,0.105,0.025,0.007,0.187,1
16,Iowa,0.668,0.080,0.114,0.012,0.006,0.118,1
17,Kansas,0.640,0.072,0.071,0.017,0.024,0.177,1
18,Kentucky,0.564,0.056,0.130,0.030,0.018,0.201,1
19,Louisiana,0.525,0.066,0.129,0.022,0.014,0.244,1
20,Maine,0.574,0.059,0.204,0.019,0.019,0.125,1
21,Maryland,0.675,0.062,0.099,0.015,0.019,0.130,1
22,Massachusetts,0.680,0.066,0.193,0.012,0.004,0.045,1
23,Michigan,0.608,0.057,0.153,0.021,0.005,0.155,1
24,Minnesota,0.671,0.081,0.130,0.015,0.006,0.097,1
25,Mississippi,0.517,0.049,0.145,0.029,0.018,0.242,1
26,Missouri,0.616,0.068,0.102,0.023,0.015,0.176,1
27,Montana,0.565,0.103,0.072,0.023,0.024,0.212,1
28,Nebraska,0.641,0.093,0.077,0.012,0.022,0.154,1
29,Nevada,0.580,0.057,0.066,0.016,0.018,0.264,1
30,New Hampshire,0.698,0.055,0.075,0.021,0.009,0.141,1
31,New Jersey,0.672,0.051,0.102,0.015,0.003,0.157,1
32,New Mexico,0.489,0.064,0.149,0.016,0.023,0.258,1
33,New York,0.609,0.049,0.185,0.016,0.004,0.137,1
34,North Carolina,0.556,0.070,0.107,0.025,0.029,0.213,1
35,North Dakota,0.673,0.104,0.063,0.012,0.030,0.118,1
36,Ohio,0.637,0.050,0.131,0.022,0.007,0.152,1
37,Oklahoma,0.552,0.058,0.092,0.026,0.022,0.249,1
38,Oregon,0.575,0.085,0.100,0.018,0.010,0.214,1
39,Pennsylvania,0.652,0.066,0.131,0.019,0.005,0.126,1
40,Rhode Island,0.635,0.051,0.147,0.014,0.014,0.139,1
41,South Carolina,0.557,0.052,0.117,0.027,0.026,0.220,1
42,South Dakota,0.616,0.112,0.073,0.014,0.029,0.157,1
43,Tennessee,0.566,0.065,0.143,0.026,0.021,0.179,1
44,Texas,0.534,0.050,0.083,0.015,0.018,0.299,1
45,Utah,0.637,0.072,0.081,0.011,0.014,0.186,1
46,Vermont,0.616,0.065,0.211,0.015,0.012,0.081,1
47,Virginia,0.642,0.064,0.063,0.022,0.048,0.160,1
48,Washington,0.606,0.076,0.107,0.014,0.025,0.172,1
49,West Virginia,0.570,0.036,0.142,0.035,0.011,0.206,1
50,Wisconsin,0.661,0.057,0.158,0.012,0.008,0.105,1
51,Wyoming,0.630,0.078,0.060,0.020,0.024,0.189,1
52,Puerto Rico,0.346,0.096,0.429,0.041,0.004,0.085,1

In [5]:
# check datatypes
ins_df_2010.dtypes

Location      object
Employer     float64
Non-Group    float64
Medicaid     float64
Medicare     float64
Military     float64
Uninsured    float64
Total          int64
dtype: object

In [6]:
#convert values to percentages and then use .style.format({"column name" : "{:,.2f}%"})
employer_per = ins_df_2010["Employer"] * 100
employer_per

non_group_per = ins_df_2010["Non-Group"] * 100
non_group_per

medicaid_per = ins_df_2010["Medicaid"] * 100
medicaid_per

medicare_per = ins_df_2010["Medicare"] * 100
medicare_per

military_per = ins_df_2010["Military"] * 100
military_per

uninsured_per = ins_df_2010["Uninsured"] * 100
uninsured_per

total_per = ins_df_2010["Total"] * 100
total_per

0     100
1     100
2     100
3     100
4     100
5     100
6     100
7     100
8     100
9     100
10    100
11    100
12    100
13    100
14    100
15    100
16    100
17    100
18    100
19    100
20    100
21    100
22    100
23    100
24    100
25    100
26    100
27    100
28    100
29    100
30    100
31    100
32    100
33    100
34    100
35    100
36    100
37    100
38    100
39    100
40    100
41    100
42    100
43    100
44    100
45    100
46    100
47    100
48    100
49    100
50    100
51    100
52    100
Name: Total, dtype: int64

In [7]:
# assign locations to list for new dataframe
locations = ins_df_2010["Location"]
locations

0            United States
1                  Alabama
2                   Alaska
3                  Arizona
4                 Arkansas
5               California
6                 Colorado
7              Connecticut
8                 Delaware
9     District of Columbia
10                 Florida
11                 Georgia
12                  Hawaii
13                   Idaho
14                Illinois
15                 Indiana
16                    Iowa
17                  Kansas
18                Kentucky
19               Louisiana
20                   Maine
21                Maryland
22           Massachusetts
23                Michigan
24               Minnesota
25             Mississippi
26                Missouri
27                 Montana
28                Nebraska
29                  Nevada
30           New Hampshire
31              New Jersey
32              New Mexico
33                New York
34          North Carolina
35            North Dakota
36                    Ohio
37                Oklahoma
38                  Oregon
39            Pennsylvania
40            Rhode Island
41          South Carolina
42            South Dakota
43               Tennessee
44                   Texas
45                    Utah
46                 Vermont
47                Virginia
48              Washington
49           West Virginia
50               Wisconsin
51                 Wyoming
52             Puerto Rico
Name: Location, dtype: object

In [8]:
# make a new dataframe with percentages and without the footnotes column
us_ins_2010_df = pd.DataFrame({'Location': locations,
                               'Year': 2010,
                               'Employer': employer_per, 
                               'Non-Group': non_group_per,
                               'Medicaid': medicaid_per,
                               'Medicare': medicare_per, 
                               'Military': military_per,
                               'Uninsured': uninsured_per, 
                               'Total': total_per})
us_ins_2010_df

,Location,Year,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,2010,58.9,6.5,12.1,1.8,1.5,19.2,100
1,Alabama,2010,57.5,6.3,11.5,3.2,2.1,19.4,100
2,Alaska,2010,58.1,3.2,10.5,1.4,6.3,20.5,100
3,Arizona,2010,52.9,6.5,17.1,1.6,1.8,20.1,100
4,Arkansas,2010,52.2,5.8,11.7,4.1,1.9,24.4,100
5,California,2010,54.0,8.0,13.1,1.2,1.0,22.5,100
6,Colorado,2010,59.9,9.4,8.8,1.3,2.4,18.2,100
7,Connecticut,2010,67.9,6.1,13.0,1.9,0.7,10.4,100
8,Delaware,2010,62.9,4.6,17.2,2.6,1.5,11.2,100
9,District of Columbia,2010,62.1,5.9,23.0,1.0,0.8,7.2,100
10,Florida,2010,51.6,7.5,9.7,2.1,1.9,27.1,100
11,Georgia,2010,56.1,5.9,8.9,2.1,2.3,24.8,100
12,Hawaii,2010,66.2,6.8,12.3,1.2,5.0,8.5,100
13,Idaho,2010,56.0,10.3,7.2,1.6,1.4,23.4,100
14,Illinois,2010,61.7,6.2,12.5,1.6,0.5,17.5,100
15,Indiana,2010,61.8,5.8,10.5,2.5,0.7,18.7,100
16,Iowa,2010,66.8,8.0,11.4,1.2,0.6,11.8,100
17,Kansas,2010,64.0,7.2,7.1,1.7,2.4,17.7,100
18,Kentucky,2010,56.4,5.6,13.0,3.0,1.8,20.1,100
19,Louisiana,2010,52.5,6.6,12.9,2.2,1.4,24.4,100
20,Maine,2010,57.4,5.9,20.4,1.9,1.9,12.5,100
21,Maryland,2010,67.5,6.2,9.9,1.5,1.9,13.0,100
22,Massachusetts,2010,68.0,6.6,19.3,1.2,0.4,4.5,100
23,Michigan,2010,60.8,5.7,15.3,2.1,0.5,15.5,100
24,Minnesota,2010,67.1,8.1,13.0,1.5,0.6,9.7,100
25,Mississippi,2010,51.7,4.9,14.5,2.9,1.8,24.2,100
26,Missouri,2010,61.6,6.8,10.2,2.3,1.5,17.6,100
27,Montana,2010,56.5,10.3,7.2,2.3,2.4,21.2,100
28,Nebraska,2010,64.1,9.3,7.7,1.2,2.2,15.4,100
29,Nevada,2010,58.0,5.7,6.6,1.6,1.8,26.4,100
30,New Hampshire,2010,69.8,5.5,7.5,2.1,0.9,14.1,100
31,New Jersey,2010,67.2,5.1,10.2,1.5,0.3,15.7,100
32,New Mexico,2010,48.9,6.4,14.9,1.6,2.3,25.8,100
33,New York,2010,60.9,4.9,18.5,1.6,0.4,13.7,100
34,North Carolina,2010,55.6,7.0,10.7,2.5,2.9,21.3,100
35,North Dakota,2010,67.3,10.4,6.3,1.2,3.0,11.8,100
36,Ohio,2010,63.7,5.0,13.1,2.2,0.7,15.2,100
37,Oklahoma,2010,55.2,5.8,9.2,2.6,2.2,24.9,100
38,Oregon,2010,57.5,8.5,10.0,1.8,1.0,21.4,100
39,Pennsylvania,2010,65.2,6.6,13.1,1.9,0.5,12.6,100
40,Rhode Island,2010,63.5,5.1,14.7,1.4,1.4,13.9,100
41,South Carolina,2010,55.7,5.2,11.7,2.7,2.6,22.0,100
42,South Dakota,2010,61.6,11.2,7.3,1.4,2.9,15.7,100
43,Tennessee,2010,56.6,6.5,14.3,2.6,2.1,17.9,100
44,Texas,2010,53.4,5.0,8.3,1.5,1.8,29.9,100
45,Utah,2010,63.7,7.2,8.1,1.1,1.4,18.6,100
46,Vermont,2010,61.6,6.5,21.1,1.5,1.2,8.1,100
47,Virginia,2010,64.2,6.4,6.3,2.2,4.8,16.0,100
48,Washington,2010,60.6,7.6,10.7,1.4,2.5,17.2,100
49,West Virginia,2010,57.0,3.6,14.2,3.5,1.1,20.6,100
50,Wisconsin,2010,66.1,5.7,15.8,1.2,0.8,10.5,100
51,Wyoming,2010,63.0,7.8,6.0,2.0,2.4,18.9,100
52,Puerto Rico,2010,34.6,9.6,42.9,4.1,0.4,8.5,100

## US insurance coverage 2012: Health Insurance Coverage of Females 19-64

In [9]:
ins_df_2012.head()

,Location,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,0.585,0.064,0.128,0.020,0.015,0.188,1
1,Alabama,0.569,0.064,0.120,0.036,0.022,0.190,1
2,Alaska,0.550,0.035,0.118,NaN,0.050,0.240,1
3,Arizona,0.526,0.071,0.160,0.017,0.019,0.207,1
4,Arkansas,0.539,0.057,0.113,0.039,0.018,0.235,1

In [10]:
# check datatypes
ins_df_2012.dtypes

Location      object
Employer     float64
Non-Group    float64
Medicaid     float64
Medicare     float64
Military     float64
Uninsured    float64
Total          int64
dtype: object

In [11]:
#check column names (previously found extra space preceding column names)
ins_df_2012.columns

Index(['Location', 'Employer', 'Non-Group', 'Medicaid', 'Medicare', 'Military',
       'Uninsured', 'Total'],
      dtype='object')

In [12]:
#remove "N/A" from the columns 
ins_2012_clean_df = ins_df_2012.fillna(0)
ins_2012_clean_df

,Location,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,0.585,0.064,0.128,0.020,0.015,0.188,1
1,Alabama,0.569,0.064,0.120,0.036,0.022,0.190,1
2,Alaska,0.550,0.035,0.118,0.000,0.050,0.240,1
3,Arizona,0.526,0.071,0.160,0.017,0.019,0.207,1
4,Arkansas,0.539,0.057,0.113,0.039,0.018,0.235,1
5,California,0.535,0.078,0.140,0.013,0.011,0.225,1
6,Colorado,0.590,0.093,0.109,0.013,0.028,0.167,1
7,Connecticut,0.666,0.054,0.144,0.018,0.007,0.111,1
8,Delaware,0.635,0.042,0.185,0.019,0.019,0.100,1
9,District of Columbia,0.618,0.075,0.227,0.000,0.008,0.065,1
10,Florida,0.505,0.078,0.115,0.021,0.019,0.262,1
11,Georgia,0.559,0.057,0.097,0.022,0.025,0.240,1
12,Hawaii,0.636,0.063,0.141,0.014,0.067,0.079,1
13,Idaho,0.558,0.091,0.092,0.023,0.014,0.222,1
14,Illinois,0.614,0.064,0.131,0.018,0.006,0.167,1
15,Indiana,0.618,0.053,0.106,0.022,0.008,0.192,1
16,Iowa,0.667,0.081,0.123,0.014,0.008,0.107,1
17,Kansas,0.638,0.072,0.071,0.023,0.026,0.170,1
18,Kentucky,0.579,0.053,0.134,0.033,0.020,0.182,1
19,Louisiana,0.517,0.063,0.145,0.021,0.016,0.237,1
20,Maine,0.574,0.051,0.203,0.028,0.019,0.125,1
21,Maryland,0.663,0.058,0.117,0.016,0.022,0.124,1
22,Massachusetts,0.672,0.058,0.212,0.013,0.004,0.041,1
23,Michigan,0.611,0.059,0.155,0.022,0.007,0.147,1
24,Minnesota,0.681,0.073,0.129,0.018,0.008,0.091,1
25,Mississippi,0.507,0.050,0.156,0.029,0.018,0.240,1
26,Missouri,0.600,0.064,0.111,0.026,0.014,0.185,1
27,Montana,0.540,0.101,0.089,0.018,0.020,0.233,1
28,Nebraska,0.648,0.089,0.077,0.012,0.020,0.154,1
29,Nevada,0.564,0.059,0.077,0.017,0.020,0.263,1
30,New Hampshire,0.701,0.048,0.071,0.027,0.010,0.143,1
31,New Jersey,0.663,0.053,0.104,0.016,0.004,0.161,1
32,New Mexico,0.496,0.056,0.158,0.023,0.019,0.248,1
33,New York,0.607,0.048,0.194,0.018,0.004,0.130,1
34,North Carolina,0.549,0.068,0.112,0.026,0.030,0.215,1
35,North Dakota,0.662,0.106,0.062,0.010,0.021,0.139,1
36,Ohio,0.628,0.053,0.142,0.023,0.008,0.146,1
37,Oklahoma,0.547,0.057,0.100,0.030,0.021,0.245,1
38,Oregon,0.579,0.079,0.123,0.019,0.011,0.189,1
39,Pennsylvania,0.653,0.065,0.134,0.021,0.006,0.121,1
40,Rhode Island,0.640,0.054,0.146,0.018,0.011,0.131,1
41,South Carolina,0.552,0.052,0.126,0.030,0.024,0.218,1
42,South Dakota,0.620,0.099,0.088,0.018,0.027,0.149,1
43,Tennessee,0.564,0.062,0.150,0.029,0.019,0.177,1
44,Texas,0.534,0.053,0.089,0.016,0.018,0.291,1
45,Utah,0.658,0.064,0.075,0.015,0.013,0.175,1
46,Vermont,0.626,0.071,0.216,0.015,0.000,0.065,1
47,Virginia,0.642,0.064,0.070,0.022,0.047,0.156,1
48,Washington,0.601,0.078,0.104,0.017,0.026,0.174,1
49,West Virginia,0.576,0.032,0.136,0.036,0.016,0.204,1
50,Wisconsin,0.659,0.064,0.144,0.016,0.008,0.110,1
51,Wyoming,0.571,0.081,0.095,0.012,0.028,0.214,1
52,Puerto Rico,0.337,0.099,0.451,0.032,0.006,0.075,1

In [13]:
#convert values to percentages and then use .style.format({"column name" : "{:,.2f}%"})
employer_per = ins_2012_clean_df["Employer"] * 100
employer_per

non_group_per = ins_2012_clean_df["Non-Group"] * 100
non_group_per

medicaid_per = ins_2012_clean_df["Medicaid"] * 100
medicaid_per

medicare_per = ins_2012_clean_df["Medicare"] * 100
medicare_per

military_per = ins_2012_clean_df["Military"] * 100
military_per

uninsured_per = ins_2012_clean_df["Uninsured"] * 100
uninsured_per

total_per = ins_2012_clean_df["Total"] * 100
total_per

0     100
1     100
2     100
3     100
4     100
5     100
6     100
7     100
8     100
9     100
10    100
11    100
12    100
13    100
14    100
15    100
16    100
17    100
18    100
19    100
20    100
21    100
22    100
23    100
24    100
25    100
26    100
27    100
28    100
29    100
30    100
31    100
32    100
33    100
34    100
35    100
36    100
37    100
38    100
39    100
40    100
41    100
42    100
43    100
44    100
45    100
46    100
47    100
48    100
49    100
50    100
51    100
52    100
Name: Total, dtype: int64

In [14]:
# assign locations to list for new dataframe
locations = ins_2012_clean_df["Location"]
locations

0            United States
1                  Alabama
2                   Alaska
3                  Arizona
4                 Arkansas
5               California
6                 Colorado
7              Connecticut
8                 Delaware
9     District of Columbia
10                 Florida
11                 Georgia
12                  Hawaii
13                   Idaho
14                Illinois
15                 Indiana
16                    Iowa
17                  Kansas
18                Kentucky
19               Louisiana
20                   Maine
21                Maryland
22           Massachusetts
23                Michigan
24               Minnesota
25             Mississippi
26                Missouri
27                 Montana
28                Nebraska
29                  Nevada
30           New Hampshire
31              New Jersey
32              New Mexico
33                New York
34          North Carolina
35            North Dakota
36                    Ohio
37                Oklahoma
38                  Oregon
39            Pennsylvania
40            Rhode Island
41          South Carolina
42            South Dakota
43               Tennessee
44                   Texas
45                    Utah
46                 Vermont
47                Virginia
48              Washington
49           West Virginia
50               Wisconsin
51                 Wyoming
52             Puerto Rico
Name: Location, dtype: object

In [26]:
# make a new dataframe with percentages and without the footnotes column
us_ins_2012_df = pd.DataFrame({'Location': locations,
                               'Year': 2012,
                               'Employer': employer_per, 
                               'Non-Group': non_group_per,
                               'Medicaid': medicaid_per,
                               'Medicare': medicare_per, 
                               'Military': military_per,
                               'Uninsured': uninsured_per, 
                               'Total': total_per})
us_ins_2012_df.head()

,Location,Year,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,2012,58.4,8.3,15.0,2.1,1.5,14.7,100
1,Alabama,2012,57.1,8.1,12.8,3.6,1.9,16.5,100
2,Alaska,2012,54.0,5.8,11.5,0.0,7.1,21.1,100
3,Arizona,2012,52.9,8.3,18.3,2.3,1.9,16.2,100
4,Arkansas,2012,52.8,8.4,17.7,3.9,1.6,15.5,100

## US Insurance Coverage 2014: Health Insurance Coverage of Females 19-64

In [19]:
ins_df_2014.head()

,Location,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,0.584,0.083,0.150,0.021,0.015,0.147,1
1,Alabama,0.571,0.081,0.128,0.036,0.019,0.165,1
2,Alaska,0.540,0.058,0.115,NaN,0.071,0.211,1
3,Arizona,0.529,0.083,0.183,0.023,0.019,0.162,1
4,Arkansas,0.528,0.084,0.177,0.039,0.016,0.155,1

In [20]:
#remove "N/A" from the columns 
ins_2014_clean_df = ins_df_2014.fillna(0)
ins_2014_clean_df

,Location,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,0.584,0.083,0.150,0.021,0.015,0.147,1
1,Alabama,0.571,0.081,0.128,0.036,0.019,0.165,1
2,Alaska,0.540,0.058,0.115,0.000,0.071,0.211,1
3,Arizona,0.529,0.083,0.183,0.023,0.019,0.162,1
4,Arkansas,0.528,0.084,0.177,0.039,0.016,0.155,1
5,California,0.538,0.094,0.187,0.015,0.010,0.155,1
6,Colorado,0.590,0.104,0.143,0.014,0.028,0.121,1
7,Connecticut,0.634,0.080,0.181,0.022,0.008,0.077,1
8,Delaware,0.648,0.047,0.184,0.026,0.018,0.077,1
9,District of Columbia,0.608,0.071,0.255,0.008,0.008,0.050,1
10,Florida,0.499,0.115,0.126,0.021,0.021,0.218,1
11,Georgia,0.566,0.077,0.105,0.023,0.023,0.206,1
12,Hawaii,0.672,0.052,0.138,0.017,0.060,0.061,1
13,Idaho,0.556,0.126,0.092,0.022,0.017,0.187,1
14,Illinois,0.620,0.080,0.158,0.019,0.006,0.118,1
15,Indiana,0.621,0.068,0.121,0.026,0.008,0.156,1
16,Iowa,0.666,0.100,0.138,0.015,0.008,0.074,1
17,Kansas,0.624,0.099,0.087,0.022,0.026,0.141,1
18,Kentucky,0.569,0.064,0.206,0.037,0.017,0.107,1
19,Louisiana,0.537,0.079,0.143,0.023,0.016,0.202,1
20,Maine,0.576,0.073,0.191,0.018,0.016,0.126,1
21,Maryland,0.650,0.072,0.148,0.018,0.019,0.092,1
22,Massachusetts,0.661,0.060,0.228,0.011,0.004,0.035,1
23,Michigan,0.606,0.079,0.181,0.024,0.006,0.105,1
24,Minnesota,0.668,0.086,0.154,0.017,0.007,0.068,1
25,Mississippi,0.520,0.074,0.164,0.029,0.019,0.195,1
26,Missouri,0.611,0.089,0.106,0.031,0.015,0.149,1
27,Montana,0.537,0.134,0.107,0.020,0.016,0.185,1
28,Nebraska,0.638,0.111,0.089,0.017,0.020,0.126,1
29,Nevada,0.577,0.070,0.126,0.021,0.020,0.185,1
30,New Hampshire,0.700,0.080,0.073,0.027,0.011,0.110,1
31,New Jersey,0.655,0.063,0.122,0.018,0.004,0.138,1
32,New Mexico,0.470,0.066,0.222,0.026,0.025,0.191,1
33,New York,0.595,0.062,0.219,0.018,0.005,0.101,1
34,North Carolina,0.553,0.101,0.118,0.026,0.029,0.174,1
35,North Dakota,0.668,0.110,0.094,0.019,0.016,0.094,1
36,Ohio,0.628,0.060,0.180,0.026,0.008,0.098,1
37,Oklahoma,0.557,0.084,0.104,0.027,0.022,0.205,1
38,Oregon,0.549,0.091,0.209,0.020,0.010,0.122,1
39,Pennsylvania,0.643,0.089,0.135,0.021,0.005,0.106,1
40,Rhode Island,0.594,0.078,0.218,0.023,0.009,0.079,1
41,South Carolina,0.546,0.074,0.135,0.032,0.027,0.186,1
42,South Dakota,0.623,0.130,0.096,0.013,0.019,0.119,1
43,Tennessee,0.549,0.085,0.164,0.028,0.021,0.153,1
44,Texas,0.548,0.078,0.092,0.017,0.018,0.246,1
45,Utah,0.650,0.101,0.072,0.012,0.013,0.152,1
46,Vermont,0.587,0.077,0.250,0.021,0.000,0.054,1
47,Virginia,0.637,0.084,0.070,0.022,0.051,0.136,1
48,Washington,0.599,0.088,0.153,0.020,0.029,0.111,1
49,West Virginia,0.564,0.039,0.233,0.039,0.011,0.114,1
50,Wisconsin,0.658,0.082,0.150,0.017,0.008,0.086,1
51,Wyoming,0.630,0.088,0.094,0.010,0.019,0.159,1
52,Puerto Rico,0.310,0.098,0.488,0.040,0.005,0.060,1

In [21]:
#convert values to percentages and then use .style.format({"column name" : "{:,.2f}%"})
employer_per = ins_2014_clean_df["Employer"] * 100
employer_per

non_group_per = ins_2014_clean_df["Non-Group"] * 100
non_group_per

medicaid_per = ins_2014_clean_df["Medicaid"] * 100
medicaid_per

medicare_per = ins_2014_clean_df["Medicare"] * 100
medicare_per

military_per = ins_2014_clean_df["Military"] * 100
military_per

uninsured_per = ins_2014_clean_df["Uninsured"] * 100
uninsured_per

total_per = ins_2014_clean_df["Total"] * 100
total_per

0     100
1     100
2     100
3     100
4     100
5     100
6     100
7     100
8     100
9     100
10    100
11    100
12    100
13    100
14    100
15    100
16    100
17    100
18    100
19    100
20    100
21    100
22    100
23    100
24    100
25    100
26    100
27    100
28    100
29    100
30    100
31    100
32    100
33    100
34    100
35    100
36    100
37    100
38    100
39    100
40    100
41    100
42    100
43    100
44    100
45    100
46    100
47    100
48    100
49    100
50    100
51    100
52    100
Name: Total, dtype: int64

In [23]:
# assign locations to list for new dataframe
locations = ins_2014_clean_df["Location"]
locations

0            United States
1                  Alabama
2                   Alaska
3                  Arizona
4                 Arkansas
5               California
6                 Colorado
7              Connecticut
8                 Delaware
9     District of Columbia
10                 Florida
11                 Georgia
12                  Hawaii
13                   Idaho
14                Illinois
15                 Indiana
16                    Iowa
17                  Kansas
18                Kentucky
19               Louisiana
20                   Maine
21                Maryland
22           Massachusetts
23                Michigan
24               Minnesota
25             Mississippi
26                Missouri
27                 Montana
28                Nebraska
29                  Nevada
30           New Hampshire
31              New Jersey
32              New Mexico
33                New York
34          North Carolina
35            North Dakota
36                    Ohio
37                Oklahoma
38                  Oregon
39            Pennsylvania
40            Rhode Island
41          South Carolina
42            South Dakota
43               Tennessee
44                   Texas
45                    Utah
46                 Vermont
47                Virginia
48              Washington
49           West Virginia
50               Wisconsin
51                 Wyoming
52             Puerto Rico
Name: Location, dtype: object

In [25]:
# make a new dataframe with percentages and without the footnotes column
us_ins_2014_df = pd.DataFrame({'Location': locations,
                               'Year': 2014,
                               'Employer': employer_per, 
                               'Non-Group': non_group_per,
                               'Medicaid': medicaid_per,
                               'Medicare': medicare_per, 
                               'Military': military_per,
                               'Uninsured': uninsured_per, 
                               'Total': total_per})
us_ins_2014_df.head()

,Location,Year,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,2014,58.4,8.3,15.0,2.1,1.5,14.7,100
1,Alabama,2014,57.1,8.1,12.8,3.6,1.9,16.5,100
2,Alaska,2014,54.0,5.8,11.5,0.0,7.1,21.1,100
3,Arizona,2014,52.9,8.3,18.3,2.3,1.9,16.2,100
4,Arkansas,2014,52.8,8.4,17.7,3.9,1.6,15.5,100

## US Insurance Coverage 2016: Health Insurance Coverage of Females 19-64

In [28]:
ins_df_2016

,Location,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,0.592,0.093,0.173,0.021,0.015,0.106,1
1,Alabama,0.587,0.091,0.138,0.038,0.019,0.127,1
2,Alaska,0.548,0.052,0.149,0.013,0.059,0.179,1
3,Arizona,0.539,0.089,0.220,0.019,0.017,0.116,1
4,Arkansas,0.532,0.093,0.220,0.035,0.016,0.103,1
5,California,0.550,0.097,0.240,0.014,0.010,0.088,1
6,Colorado,0.600,0.104,0.171,0.015,0.024,0.085,1
7,Connecticut,0.639,0.083,0.194,0.017,0.007,0.059,1
8,Delaware,0.654,0.069,0.176,0.023,0.017,0.061,1
9,District of Columbia,0.602,0.086,0.260,0.008,0.008,0.036,1
10,Florida,0.509,0.145,0.136,0.024,0.020,0.166,1
11,Georgia,0.574,0.099,0.111,0.022,0.027,0.168,1
12,Hawaii,0.684,0.064,0.144,0.014,0.052,0.043,1
13,Idaho,0.577,0.137,0.105,0.020,0.014,0.147,1
14,Illinois,0.630,0.087,0.180,0.018,0.006,0.079,1
15,Indiana,0.637,0.077,0.154,0.025,0.008,0.099,1
16,Iowa,0.671,0.092,0.169,0.015,0.008,0.045,1
17,Kansas,0.653,0.104,0.090,0.019,0.025,0.108,1
18,Kentucky,0.560,0.066,0.263,0.039,0.017,0.055,1
19,Louisiana,0.534,0.096,0.200,0.024,0.013,0.132,1
20,Maine,0.593,0.108,0.172,0.019,0.018,0.090,1
21,Maryland,0.656,0.082,0.153,0.019,0.021,0.069,1
22,Massachusetts,0.651,0.069,0.237,0.012,0.005,0.026,1
23,Michigan,0.612,0.080,0.218,0.023,0.005,0.062,1
24,Minnesota,0.666,0.091,0.170,0.018,0.007,0.048,1
25,Mississippi,0.538,0.079,0.168,0.034,0.020,0.161,1
26,Missouri,0.628,0.105,0.101,0.035,0.014,0.118,1
27,Montana,0.558,0.132,0.170,0.017,0.024,0.099,1
28,Nebraska,0.662,0.114,0.081,0.013,0.017,0.113,1
29,Nevada,0.575,0.085,0.168,0.015,0.021,0.136,1
30,New Hampshire,0.695,0.077,0.112,0.025,0.009,0.082,1
31,New Jersey,0.662,0.074,0.146,0.021,0.004,0.093,1
32,New Mexico,0.475,0.076,0.294,0.024,0.026,0.105,1
33,New York,0.592,0.071,0.248,0.016,0.005,0.068,1
34,North Carolina,0.563,0.113,0.129,0.030,0.029,0.137,1
35,North Dakota,0.670,0.122,0.087,0.014,0.026,0.082,1
36,Ohio,0.631,0.067,0.206,0.026,0.008,0.063,1
37,Oklahoma,0.558,0.091,0.111,0.035,0.020,0.185,1
38,Oregon,0.571,0.106,0.220,0.020,0.008,0.076,1
39,Pennsylvania,0.637,0.090,0.179,0.024,0.005,0.064,1
40,Rhode Island,0.621,0.091,0.215,0.024,0.007,0.042,1
41,South Carolina,0.574,0.097,0.148,0.030,0.024,0.128,1
42,South Dakota,0.660,0.112,0.088,0.021,0.027,0.093,1
43,Tennessee,0.569,0.091,0.180,0.026,0.020,0.114,1
44,Texas,0.566,0.092,0.087,0.017,0.019,0.219,1
45,Utah,0.674,0.109,0.087,0.011,0.013,0.106,1
46,Vermont,0.615,0.080,0.249,0.015,NaN,0.037,1
47,Virginia,0.644,0.095,0.080,0.023,0.050,0.108,1
48,Washington,0.617,0.086,0.184,0.017,0.027,0.069,1
49,West Virginia,0.557,0.047,0.293,0.035,0.013,0.055,1
50,Wisconsin,0.669,0.091,0.152,0.017,0.009,0.062,1
51,Wyoming,0.633,0.107,0.095,0.013,0.030,0.122,1
52,Puerto Rico,0.307,0.099,0.482,0.040,0.004,0.068,1

In [29]:
#remove "N/A" from the columns 
ins_2016_clean_df = ins_df_2016.fillna(0)
ins_2016_clean_df

,Location,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,0.592,0.093,0.173,0.021,0.015,0.106,1
1,Alabama,0.587,0.091,0.138,0.038,0.019,0.127,1
2,Alaska,0.548,0.052,0.149,0.013,0.059,0.179,1
3,Arizona,0.539,0.089,0.220,0.019,0.017,0.116,1
4,Arkansas,0.532,0.093,0.220,0.035,0.016,0.103,1
5,California,0.550,0.097,0.240,0.014,0.010,0.088,1
6,Colorado,0.600,0.104,0.171,0.015,0.024,0.085,1
7,Connecticut,0.639,0.083,0.194,0.017,0.007,0.059,1
8,Delaware,0.654,0.069,0.176,0.023,0.017,0.061,1
9,District of Columbia,0.602,0.086,0.260,0.008,0.008,0.036,1
10,Florida,0.509,0.145,0.136,0.024,0.020,0.166,1
11,Georgia,0.574,0.099,0.111,0.022,0.027,0.168,1
12,Hawaii,0.684,0.064,0.144,0.014,0.052,0.043,1
13,Idaho,0.577,0.137,0.105,0.020,0.014,0.147,1
14,Illinois,0.630,0.087,0.180,0.018,0.006,0.079,1
15,Indiana,0.637,0.077,0.154,0.025,0.008,0.099,1
16,Iowa,0.671,0.092,0.169,0.015,0.008,0.045,1
17,Kansas,0.653,0.104,0.090,0.019,0.025,0.108,1
18,Kentucky,0.560,0.066,0.263,0.039,0.017,0.055,1
19,Louisiana,0.534,0.096,0.200,0.024,0.013,0.132,1
20,Maine,0.593,0.108,0.172,0.019,0.018,0.090,1
21,Maryland,0.656,0.082,0.153,0.019,0.021,0.069,1
22,Massachusetts,0.651,0.069,0.237,0.012,0.005,0.026,1
23,Michigan,0.612,0.080,0.218,0.023,0.005,0.062,1
24,Minnesota,0.666,0.091,0.170,0.018,0.007,0.048,1
25,Mississippi,0.538,0.079,0.168,0.034,0.020,0.161,1
26,Missouri,0.628,0.105,0.101,0.035,0.014,0.118,1
27,Montana,0.558,0.132,0.170,0.017,0.024,0.099,1
28,Nebraska,0.662,0.114,0.081,0.013,0.017,0.113,1
29,Nevada,0.575,0.085,0.168,0.015,0.021,0.136,1
30,New Hampshire,0.695,0.077,0.112,0.025,0.009,0.082,1
31,New Jersey,0.662,0.074,0.146,0.021,0.004,0.093,1
32,New Mexico,0.475,0.076,0.294,0.024,0.026,0.105,1
33,New York,0.592,0.071,0.248,0.016,0.005,0.068,1
34,North Carolina,0.563,0.113,0.129,0.030,0.029,0.137,1
35,North Dakota,0.670,0.122,0.087,0.014,0.026,0.082,1
36,Ohio,0.631,0.067,0.206,0.026,0.008,0.063,1
37,Oklahoma,0.558,0.091,0.111,0.035,0.020,0.185,1
38,Oregon,0.571,0.106,0.220,0.020,0.008,0.076,1
39,Pennsylvania,0.637,0.090,0.179,0.024,0.005,0.064,1
40,Rhode Island,0.621,0.091,0.215,0.024,0.007,0.042,1
41,South Carolina,0.574,0.097,0.148,0.030,0.024,0.128,1
42,South Dakota,0.660,0.112,0.088,0.021,0.027,0.093,1
43,Tennessee,0.569,0.091,0.180,0.026,0.020,0.114,1
44,Texas,0.566,0.092,0.087,0.017,0.019,0.219,1
45,Utah,0.674,0.109,0.087,0.011,0.013,0.106,1
46,Vermont,0.615,0.080,0.249,0.015,0.000,0.037,1
47,Virginia,0.644,0.095,0.080,0.023,0.050,0.108,1
48,Washington,0.617,0.086,0.184,0.017,0.027,0.069,1
49,West Virginia,0.557,0.047,0.293,0.035,0.013,0.055,1
50,Wisconsin,0.669,0.091,0.152,0.017,0.009,0.062,1
51,Wyoming,0.633,0.107,0.095,0.013,0.030,0.122,1
52,Puerto Rico,0.307,0.099,0.482,0.040,0.004,0.068,1

In [30]:
#convert values to percentages and then use .style.format({"column name" : "{:,.2f}%"})
employer_per = ins_2016_clean_df["Employer"] * 100
employer_per

non_group_per = ins_2016_clean_df["Non-Group"] * 100
non_group_per

medicaid_per = ins_2016_clean_df["Medicaid"] * 100
medicaid_per

medicare_per = ins_2016_clean_df["Medicare"] * 100
medicare_per

military_per = ins_2016_clean_df["Military"] * 100
military_per

uninsured_per = ins_2016_clean_df["Uninsured"] * 100
uninsured_per

total_per = ins_2016_clean_df["Total"] * 100
total_per

0     100
1     100
2     100
3     100
4     100
5     100
6     100
7     100
8     100
9     100
10    100
11    100
12    100
13    100
14    100
15    100
16    100
17    100
18    100
19    100
20    100
21    100
22    100
23    100
24    100
25    100
26    100
27    100
28    100
29    100
30    100
31    100
32    100
33    100
34    100
35    100
36    100
37    100
38    100
39    100
40    100
41    100
42    100
43    100
44    100
45    100
46    100
47    100
48    100
49    100
50    100
51    100
52    100
Name: Total, dtype: int64

In [32]:
# assign locations to list for new dataframe
locations = ins_2016_clean_df["Location"]

In [34]:
# make a new dataframe with percentages and without the footnotes column
us_ins_2016_df = pd.DataFrame({'Location': locations,
                               'Year': 2016,
                               'Employer': employer_per, 
                               'Non-Group': non_group_per,
                               'Medicaid': medicaid_per,
                               'Medicare': medicare_per, 
                               'Military': military_per,
                               'Uninsured': uninsured_per, 
                               'Total': total_per})
us_ins_2016_df.head()

,Location,Year,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,2016,59.2,9.3,17.3,2.1,1.5,10.6,100
1,Alabama,2016,58.7,9.1,13.8,3.8,1.9,12.7,100
2,Alaska,2016,54.8,5.2,14.9,1.3,5.9,17.9,100
3,Arizona,2016,53.9,8.9,22.0,1.9,1.7,11.6,100
4,Arkansas,2016,53.2,9.3,22.0,3.5,1.6,10.3,100

## US insurance coverage 2018 : Health Insurance Coverage of Females 19-64

In [36]:
ins_df_2018.head()

,Location,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,0.602,0.083,0.170,0.020,0.015,0.110,1
1,Alabama,0.588,0.075,0.137,0.036,0.025,0.139,1
2,Alaska,0.556,0.054,0.176,NaN,0.062,0.136,1
3,Arizona,0.555,0.074,0.200,0.020,0.018,0.134,1
4,Arkansas,0.534,0.081,0.237,0.036,0.012,0.100,1

In [37]:
#remove "N/A" from the columns 
ins_2018_clean_df = ins_df_2018.fillna(0)
ins_2018_clean_df

,Location,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,0.602,0.083,0.170,0.020,0.015,0.110,1
1,Alabama,0.588,0.075,0.137,0.036,0.025,0.139,1
2,Alaska,0.556,0.054,0.176,0.000,0.062,0.136,1
3,Arizona,0.555,0.074,0.200,0.020,0.018,0.134,1
4,Arkansas,0.534,0.081,0.237,0.036,0.012,0.100,1
5,California,0.562,0.095,0.235,0.013,0.010,0.086,1
6,Colorado,0.619,0.093,0.162,0.016,0.024,0.086,1
7,Connecticut,0.650,0.076,0.192,0.015,0.006,0.062,1
8,Delaware,0.630,0.060,0.209,0.023,0.014,0.063,1
9,District of Columbia,0.613,0.094,0.247,0.000,0.007,0.032,1
10,Florida,0.526,0.137,0.122,0.022,0.020,0.174,1
11,Georgia,0.592,0.077,0.107,0.022,0.026,0.177,1
12,Hawaii,0.679,0.067,0.148,0.011,0.057,0.038,1
13,Idaho,0.589,0.123,0.094,0.017,0.019,0.158,1
14,Illinois,0.644,0.075,0.168,0.017,0.006,0.090,1
15,Indiana,0.650,0.064,0.154,0.024,0.007,0.101,1
16,Iowa,0.674,0.073,0.175,0.014,0.007,0.057,1
17,Kansas,0.667,0.079,0.095,0.019,0.025,0.115,1
18,Kentucky,0.572,0.056,0.255,0.034,0.016,0.067,1
19,Louisiana,0.527,0.070,0.267,0.025,0.017,0.094,1
20,Maine,0.609,0.098,0.157,0.019,0.018,0.099,1
21,Maryland,0.660,0.070,0.162,0.018,0.020,0.070,1
22,Massachusetts,0.651,0.074,0.229,0.011,0.005,0.030,1
23,Michigan,0.620,0.070,0.218,0.024,0.005,0.063,1
24,Minnesota,0.693,0.073,0.168,0.015,0.007,0.044,1
25,Mississippi,0.552,0.071,0.162,0.031,0.017,0.166,1
26,Missouri,0.645,0.080,0.110,0.030,0.015,0.121,1
27,Montana,0.571,0.111,0.182,0.017,0.024,0.094,1
28,Nebraska,0.672,0.089,0.090,0.014,0.022,0.112,1
29,Nevada,0.581,0.069,0.168,0.018,0.023,0.141,1
30,New Hampshire,0.705,0.066,0.126,0.031,0.010,0.062,1
31,New Jersey,0.676,0.072,0.140,0.018,0.004,0.090,1
32,New Mexico,0.466,0.065,0.310,0.022,0.021,0.116,1
33,New York,0.602,0.072,0.245,0.017,0.004,0.060,1
34,North Carolina,0.586,0.092,0.125,0.026,0.030,0.141,1
35,North Dakota,0.670,0.101,0.096,0.027,0.025,0.081,1
36,Ohio,0.629,0.061,0.205,0.023,0.008,0.075,1
37,Oklahoma,0.572,0.083,0.107,0.030,0.021,0.186,1
38,Oregon,0.588,0.089,0.204,0.018,0.012,0.089,1
39,Pennsylvania,0.650,0.075,0.185,0.021,0.006,0.063,1
40,Rhode Island,0.640,0.068,0.215,0.020,0.011,0.046,1
41,South Carolina,0.572,0.088,0.147,0.028,0.027,0.138,1
42,South Dakota,0.659,0.108,0.089,0.015,0.025,0.104,1
43,Tennessee,0.573,0.079,0.170,0.028,0.021,0.128,1
44,Texas,0.568,0.080,0.088,0.016,0.018,0.229,1
45,Utah,0.669,0.114,0.083,0.013,0.014,0.107,1
46,Vermont,0.635,0.083,0.209,0.021,0.000,0.044,1
47,Virginia,0.652,0.083,0.085,0.025,0.050,0.105,1
48,Washington,0.630,0.074,0.178,0.015,0.022,0.080,1
49,West Virginia,0.560,0.046,0.266,0.037,0.011,0.080,1
50,Wisconsin,0.685,0.078,0.144,0.016,0.007,0.070,1
51,Wyoming,0.640,0.111,0.082,0.014,0.021,0.132,1
52,Puerto Rico,0.304,0.100,0.485,0.037,0.006,0.068,1

In [38]:
#convert values to percentages and then use .style.format({"column name" : "{:,.2f}%"})
employer_per = ins_2018_clean_df["Employer"] * 100
employer_per

non_group_per = ins_2018_clean_df["Non-Group"] * 100
non_group_per

medicaid_per = ins_2018_clean_df["Medicaid"] * 100
medicaid_per

medicare_per = ins_2018_clean_df["Medicare"] * 100
medicare_per

military_per = ins_2018_clean_df["Military"] * 100
military_per

uninsured_per = ins_2018_clean_df["Uninsured"] * 100
uninsured_per

total_per = ins_2018_clean_df["Total"] * 100
total_per

0     100
1     100
2     100
3     100
4     100
5     100
6     100
7     100
8     100
9     100
10    100
11    100
12    100
13    100
14    100
15    100
16    100
17    100
18    100
19    100
20    100
21    100
22    100
23    100
24    100
25    100
26    100
27    100
28    100
29    100
30    100
31    100
32    100
33    100
34    100
35    100
36    100
37    100
38    100
39    100
40    100
41    100
42    100
43    100
44    100
45    100
46    100
47    100
48    100
49    100
50    100
51    100
52    100
Name: Total, dtype: int64

In [39]:
# assign locations to list for new dataframe
locations = ins_2018_clean_df["Location"]

In [40]:
# make a new dataframe with percentages and without the footnotes column
us_ins_2018_df = pd.DataFrame({'Location': locations,
                               'Year': 2018,
                               'Employer': employer_per, 
                               'Non-Group': non_group_per,
                               'Medicaid': medicaid_per,
                               'Medicare': medicare_per, 
                               'Military': military_per,
                               'Uninsured': uninsured_per, 
                               'Total': total_per})
us_ins_2018_df.head()

,Location,Year,Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,Total
0,United States,2018,60.2,8.3,17.0,2.0,1.5,11.0,100
1,Alabama,2018,58.8,7.5,13.7,3.6,2.5,13.9,100
2,Alaska,2018,55.6,5.4,17.6,0.0,6.2,13.6,100
3,Arizona,2018,55.5,7.4,20.0,2.0,1.8,13.4,100
4,Arkansas,2018,53.4,8.1,23.7,3.6,1.2,10.0,100